name: C++23 Build and Test

on:
  push:
    branches: [ "main" ]
    paths-ignore: &ignored_paths
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.clangd'
      - '.clang-format'
      - '.clang-tidy'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore: *ignored_paths

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_CXX_STANDARD=23
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DNTD_BUILD_TESTS=ON

      - name: Build the project
        run: cmake --build ${{github.workspace}}/build --config Release --parallel 4

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release --output-on-failure
